version: '2'
services:
    notification_client_php:
        build: docker/images/php
        volumes:
            - ./docker/config/apache2:/etc/apache2/sites-enabled
            - ./docker/config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/var/www/html
        container_name: notification-client_php
        networks:
            - vpcbr
        ports:
            - 9052:80
networks:
  vpcbr:
    external:
      name: vpcbr
